### ISSUE TITLE
RayCastInput not storing input arguments

### ISSUE THREAD

**Issue by paulhayes** [HBehrens/box2d.js#13]
When the RayCaseInput method is used, for instance in the b2World RayCast method, it is handed two b2Vec2 objects in the constructor function. However RayCast is failing for me, and when I looked at all the instances of RayCastInput being used, p1 and p2 the two instances of b2Vec2 objects had values of 0,0. Further investigation revealed the b2RayCastInput constructor seems to discard any arguments handed to it.

Is my observation correct, or am i missing something?

**Comment by HBehrens** [comment]
been on vacation. Will look into this tonight.

**Comment by HBehrens** [comment]
since there are no unit-tests in this project could you please double check it's fixed?

**Comment by paulhayes** [comment]
I'll give it a go, thanks. Will be two or three days before I get a chance.
